### ISSUE TITLE
gym.error.UnregisteredEnv: No registered env with id: flashgames.NeonRace-v0

### ISSUE THREAD

**Issue by mludvig** [sudharsan13296/Hands-On-Reinforcement-Learning-With-Python#2]
Hi there
I just got your book in the mail and going through _Chapter 2 - Building a video game bot_. 
The previous three examples worked (`CartPole`, `CarRacing`, `BipedalWalter`) but the `flashgames.NeonRace-v0` doesn't, it fails with this error:

    gym.error.UnregisteredEnv: No registered env with id: flashgames.NeonRace-v0

I've got `gym==0.7.0` installed as suggested and followed all the other instructions. 

Any idea what's wrong?
Cheers

**Comment by blessdyb** [comment]
My environment:

`MacOS==10.13.6`/`gym==0.7.4`/`universe==3`
* Install XCode Command Line Tools first `xcode-select --install`
* `pip install Box2D box2d box2d-kengz`
* `pip install docker-py --upgrade` (https://github.com/openai/universe/issues/165)

After this, everything is working.
